spring.application.name=sb-ecom

spring.h2.console.enabled=true

#if we need same h2db url as on every restart app it changes
#we should fix it as mem:anyname here i gave test

spring.datasource.url=jdbc:h2:mem:test

#if we breakdown this url meanining would be
#jdbc it is protocol to connect
#h2 it is db engine or db
#mem means in memory
#test is the name


#so let's have a look for internal working
#implementation is done by Hibernate
#to do so:

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


